apiVersion: v1
kind: Service
metadata:
  labels:
    app: php
  name: php-hello-world-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: php
