kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-volume
spec:
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/d8-mysql
  capacity:
      storage: 2Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: drupal-volume
spec:
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/drupal
  capacity:
      storage: 2Gi
